In [74]:
from webScrappingArticles import reading_scrapped_news

In [78]:
returned_df = reading_scrapped_news()

Scraping: https://www.espn.in/football/
Error processing article: 'href'
Scraping: https://www.espn.in/cricket/
Error processing article: 'href'
Scraping: https://www.espn.in/badminton/
Error processing article: 'href'
Scraping: https://www.espn.in/
Error processing article: 'href'
Error scraping No link: Invalid URL 'No link': No scheme supplied. Perhaps you meant https://No link?
Error scraping No link: Invalid URL 'No link': No scheme supplied. Perhaps you meant https://No link?
Error scraping No link: Invalid URL 'No link': No scheme supplied. Perhaps you meant https://No link?
Error scraping No link: Invalid URL 'No link': No scheme supplied. Perhaps you meant https://No link?

In [80]:
import json 

json_records = returned_df.to_dict(orient='records')

# Convert to JSON string (optional)
# json_response = json.dumps(json_records, indent=4)

In [82]:
json_records

[{'title': "Liverpool, Salah show Chelsea's kids why experience matters",
  'summary': "Mo Salah didn't have the best game, but a goal and assist were enough to beat Chelsea and prove that continuity is better than constant change.",
  'label': 'football',
  'full_link': 'https://www.espn.in/football/story/_/id/41905256/liverpool-salah-show-chelsea-kids-why-experience-matters',
  'scrappe_news2': {'title': "Liverpool, Salah show Chelsea's kids why experience matters",
   'content': 'LIVERPOOL, England -- A game which brought together two sides building for the future was decided by a player whose legacy has long since been established. There wasn\'t much betweenLiverpoolandChelseaat Anfield on Sunday but the home side prevailed with a 2-1 victory which took them back to thePremier Leaguesummit courtesy ofMohamed Salah\'s enduring ability to deliver match-defining moments. Salah was not at his devastating best -- midfielderCurtis Jonesproduced a memorable all-action display en route to netting the winning goal on 51 minutes -- but the 32-year-old forward produced a sublime cross to assist him after earlier opening the scoring from the penalty spot. It is the 34th time he has registered a goal and assist in a Premier League game -- only Wayne Rooney (36) has done it more often. And, after Chelsea had looked the better side early on, his emphatically converted 29th-minute penalty wrestled control of the game in Liverpool\'s favour and took his league tally to 162, tied with Jermain Defoe at ninth on the all-time goal-scorers list. His 232 goal involvements also puts him tied sixth along withManchester Citylegend Sergio Aguero on that measure. This continuation of Salah\'s end product has helped new manager Arne Slot settle in smoothly to the daunting task of replacing Jurgen Klopp on Merseyside, with seven wins from his first eight league games to top the table. TheEgyptinternational has seven goals in 11 games across all competitions this season and perhaps benefitted from a freshness engineered by the decision not to play for his country inMauritaniaa few days earlier due to a heightened risk of injury from that match taking place on a plastic pitch. Slot knows he needs that buy-in from Liverpool\'s talisman -- with new contract talks looming as his existing deal approaches the final six months -- also explaining why he highlighted his work off the ball as the home side hung on to their lead. "He is important for us, for the numbers he has but it was a bit of a funny remark after the game, I said to Trent [Alexander-Arnold] \'you have some competition now\' because I saw today that Mo can play as a right full-back as well," Slot said afterwards. "So the defensive effort he put in today to help the team in that part is what pleased me just as much as his goal and assist." Liverpool needed to put in a defensive shift as Chelsea put in a performance which will encourage Blues boss Enzo Maresca that they are on the right track: the Blues had more touches in the opposition box in the first half of a league game than any other team in four years, registered 57% possession, and had consistent spells where they looked more threatening. Cole Palmeris a wondrous talent but, in contrast to Salah, he wasn\'t quite able to influence proceedings as he would have liked, firing over just before the interval and wasting a couple of shooting opportunities in the second half. The 22-year-old is quickly establishing himself as one of the Premier League\'s finest match winners, but Salah has held that status for years. In recent times, Chelsea have deliberately pursued a policy of predominantly signing players aged 24 and under. But for all their lavish spending, they don\'t possess a battle-hardened talent of Salah\'s pedigree to help polish rough performances during a period of transition. (The enduring irony, of course, is that Chelsea signed Salah aged 21 back in 2014 but that was during an era when young players found the route to the exit door much easier than the first-team dressing room.) Salah\'s penalty -- won by Jones after a foul byLevi Colwill-- stopped Chelsea in their tracks and on another afternoon where VAR checks were frequent and lengthy, they required a review in their favour to avoid conceding a second penalty as replays showed goalkeeperRobert Sánchezjust got the ball ahead of Jones before taking him out. Chelsea equalised three minutes after the restart asNicolas JacksoncollectedMoisés Caicedo\'s pass and finished superbly pastCaoimhín Kelleher, deputising for the injured Alisson. But after Salah fed Jones, withReece Jamescaught fractionally deep and playing him onside, the England midfielder steered a fine effort past Sanchez to restore Liverpool\'s lead within moments. The Blues, to their credit, were undeterred. They were beaten 4-1 here back in January under Mauricio Pochettino, yet they finished the game the stronger side this time. It just wasn\'t enough. In the final phase we saw perhaps the clearest distinction between Slot\'s Liverpool side and the Klopp era. Liverpool\'s full-backs stopped going forward; Slot replacedTrent Alexander-Arnoldwith the more defensive-mindedJoe Gomezfor the final nine minutes; and Jones, who had been marauding forward from midfield, was replaced at the same time byAlexis Mac Allister. TheArgentinainternational sat deep alongsideRyan Gravenberchand tried to deny Chelsea any space in which to play. It contributed to a nervy finale, but Slot is not Klopp, whose inclination would been to go for the kill when Chelsea wavered after falling behind at 1-0 and, briefly, at 2-1. Both sides are trying to implement fresh ideas and building belief. Slot is attempting tweaks rather than wholesale changes and that more-settled environment gave Liverpool the edge over Chelsea, who started life under their new manager with another aggressive overhaul of their squad. "We don\'t like losing games, dropping points but if you have to decide the way, then this is probably the way," Maresca said afterwards. "I\'ve been in the stadium many times and have seen Liverpool for a long time -- it\'s not easy. I think overall, we controlled the game and for most parts of the game we dominated the game, but we lost." Chelsea\'s defending must improve after just two clean sheets in eight league games; Liverpool can look ahead with greater optimism. "The better the teams you face the more you need [fight]," Slot said. "In the Premier League, there are so many good teams so if you want to win at least you need to fight and then hopefully the individuals can make the difference." Salah continues to do just that.'}},
 {'title': 'Player ratings: Arsenal suffer first loss of season with poor Saliba, Trossard showings',
  'summary': 'Arsenal suffered their first loss of the 2024-25 Premier League season after lowlight-worthy performances from Saliba and Trossard.',
  'label': 'football',
  'full_link': 'https://www.espn.in/football/story/_/id/41886206/arsenal-player-ratings-first-defeat-2024-25-season-saliba-trossard',
  'scrappe_news2': {'title': 'Arsenal ratings: First loss of season due to Saliba, Trossard',
   'content': 'Arsenalsuffered their first loss of the season on Saturday as they fell 2-0 toBournemouthat the Vitality Stadium. The Gunners had control of the game until the 30th minute, whenLeandro Trossard\'s careless pass leftWilliam Salibain trouble before earning red for a foul that VAR deemed to have deniedEvanilsona clear goal-scoring opportunity. Some positive moments of goalkeeping byDavid Rayaensured Arsenal held Bournemouth scoreless by the break. Antoine Semenyowas one of Bournemouth\'s brightest as the Cherries began to create chances, though he should have done better moments after the restart with an effort at the backpost that was struck off target. Arsenal could have taken the lead with their best chance of the match whenMikel MerinointerceptedKepa Arrizabalaga\'s pass before picking out substituteGabriel Martinelli, only for him to strike the ball straight at the goalkeeper. That miss proved to be costly as they went behind two minutes later, withRyan Christiefinishing off a well-taken Bournemouth corner. An under-hit pass byJakub Kiwiorled to Raya giving away a penalty for the home side to double the lead throughJustin Kluivert, and the Gunners looked resigned to defeat with Mikel Merino being withdrawn. Merino enjoyed a bright performance despite the result, and he looks to be a strong fit for Arsenal\'s system.Declan Ricewas also a standout in midfield with his defensive work. The absences of Martin Ødegaard andBukayo Sakawere noticeable in an Arsenal attack that didn\'t create many moments of promise. An upcoming suspension for William Saliba means he misses the nextPremier Leaguematch againstLiverpool. Mikel Arteta, 6 --There was little Arteta could do after individual errors were punished, but he could have seen his side go 1-0 up on another day if substitute Gabriel Martinelli converted his chance. GKDavid Raya, 5 --Raya looked uncertain when claiming crosses and he also played a misplaced ball straight to Alex Scott in the first half. While he made some saves to keep the game at 0-0, an overall inconsistent evening was compounded when he gave away a penalty. DFGabriel Magalhães, 6-- Gabriel cleared the danger on a number of occasions and registered a couple of blocks. Not as effective as usual from attacking set-pieces. DFWilliam Saliba, 4-- Saliba looked in control before he was sent off following a VAR review after he pulled down Evanilson to deny a goal-scoring opportunity. There was some distance to go, which could see the France international regret not using his pace rather than fouling. DFRiccardo Calafiori, 6-- Left Antoine Semenyo at the backpost moments into the second half, but was let off by a poor finish by the Bournemouth forward. His efforts helped create some half-chances at times when driving with the ball into midfield. DFBen White, 5-- Beaten too easily at times and picked up a booking for timewasting with the score at 0-0. MFMikel Merino, 7-- The Spain international was composed in possession, particularly in advanced areas, and he enjoyed some positive link-up play with Raheem Sterling before he was taken off after the red card. Took up intelligent positions to cut off passing lanes in the middle of the pitch, and created Arsenal\'s best chance when playing in Gabriel Martinelli following a well-timed interception on Kepa Arrizabalaga\'s pass. MFDeclan Rice, 7-- Rice provided a strong anchor when Arsenal were looking to defend with 10 men, where he regularly anticipated play to clear the danger. Worked hard to make up for the numbers advantage, and tried to progress the ball into advanced areas. MFThomas Partey, 6-- Progressed the ball impressively through the lines from defensive midfield, and also chose the right moments to drop into centre-back to create a back-three. Little he could do about either of the goals. FWKai Havertz, 6-- Havertz worked hard and tried to make things happen with minimal service, with positive runs directly at the defence that led to some half-chances. FWLeandro Trossard, 5-- Trossard\'s poor pass to Saliba led to the red card that made the game much more difficult for the Gunners. Ineffective overall, and replaced by Gabriel Martinelli in the 64th minute. FWRaheem Sterling, 5-- Stayed wide to stretch the pitch and had one moment during which he tried to cut inside and beat his marker, but didn\'t have enough opportunities to make an impact on the game. Replaced for tactical reasons after Saliba\'s red card. Jakub Kiwior(Sterling, 37"), 4 --A match to forget for Kiwior, who struggled early on with the pace of Semenyo, and after he under-hit his pass to Raya before Bournemouth\'s penalty, he was taken back off the pitch by Arteta. He was not the solution Arteta had hoped for. Gabriel Martinelli(Trossard, 64"), 5 --It didn\'t take long for Martinelli to get involved with Arsenal\'s best chance of the game five minutes after coming in, but he should have done better with the finish that was straight at Arrizabalaga. Gabriel Jesus(Kiwior, 81"), N/R-- Positive in possession and tried to make something happen by going alone with a dribbling run through the Bournemouth defence before he was eased off the ball. Ethan Nwaneri(Merino, 81") N/R-- Introduced for Merino butArsenalcouldn\'t garner any control of the game to begin a late comeback.'}},
 {'title': 'Bloodied but not beaten, Man United comeback spurred by anger and Garnacho',
  'summary': "Man United came from behind to win against Brentford after Matthijs de Ligt's head injury, and there are some signs of progress under Erik ten Hag.",
  'label': 'football',
  'full_link': 'https://www.espn.in/football/story/_/id/41884048/man-united-comeback-shows-build-garnacho',
  'scrappe_news2': {'title': 'Man United comeback shows they must build around Garnacho',
   'content': 'MANCHESTER, England --Alejandro Garnachowas given top billing by Erik ten Hag againstBrentfordand theManchester Unitedwinger repaid his under-fire manager with a performance to match. Both Garnacho andMarcus Rashfordwant to play on the left and, more often than not, Ten Hag has given preference to Rashford. But United haven\'t been scoring or winning and so the Dutchman made a change to put the England international on the right instead. It worked and Garnacho scored a crucial equaliser from the left to help United to a much-needed 2-1 win. TheArgentinainternational tormented makeshift right-backSepp van den Bergand was easily the home side\'s best player. He would have had at least two assists to add to his goal had his teammates been more alert to a couple of crosses fizzed across the penalty area during a brilliant second half. Garnacho went off late in the game to a standing ovation from the supporters inside Old Trafford. Thanks largely to the 20-year-old they finally had a good day in Manchester\'s Autumn sun, and so did Ten Hag. "I know what he\'s capable of," Ten Hag said afterwards. "He\'s a threat and has scoring abilities, but also a threat in one-versus-one situations. The end product is definitely what we need and missed that in the first games of the season." After five games without a win, Ten Hag desperately needed one. But it looked for a while that Brentford would hammer another nail into his coffin with a first league win at Old Trafford since 1937 as they went into half-time 1-0 up. Matthijs de Ligthad already been ordered off the field twice after suffering a head wound in a collision withKevin Schade. With blood still colouring his hair and face red, the centre-back was sent to the touchline for a third time in first-half stoppage time. While he was off the pitch,Ethan Pinnockgot away fromDiogo Dalotfrom a corner and headed pastAndré Onana. De Ligt spun round in a fury and booted a ball into the stands; Ruud van Nistelrooy\'s protests earned the assistant coach a yellow card and he was lucky to avoid a second as he continued his argument with the fourth official in the tunnel at the break. So often United under Ten Hag have failed to deal with setbacks. This time, though, the perceived injustice seemed to fire them up. "We were mad," Ten Hag admitted. "Definitely, we were angry at half-time." Brentford have made headlines for starting quickly in the last month, but it was United who started the second half with a bang. United\'s tactic for most of the game appeared to centre around getting the ball to Garnacho as quickly as possible and in the 47th minute it got Ten Hag\'s team back in the game. Rashford picked up the ball on the right and arrowed a pinpoint pass towards the far side of the penalty area; Garnacho has scored spectacular volleys before and added another to his collection with a guided finish into the net before the ball had touched the ground. It was the type of clinical finish Ten Hag has been begging for -- and it was one of seven shots Garnacho attempted, three more than any other United player. Sometimes criticised for his work rate, he defended as well as he attacked and topped the stats sheet with six ball recoveries before being substituted. With United 1-0 down andSouthampton2-0 up against Leicester, there was a point during the afternoon when Ten Hag\'s team were officially the Premier League\'s lowest scorers. But Ten Hag has said repeatedly that he is confident his forwards will eventually click and for 45 minutes against Brentford they did. The second goal was one straight from Ten Hag\'s drawing board. United\'s press pinned Brentford into their own corner,Lisandro Martínezcollected a loose pass high up the pitch,Christian Eriksenfired forward a quick pass, andRasmus Højlundadded a deft finish after a clever flick fromBruno Fernandes. Ten Hag\'s beaming smile said it all and he embraced both Van Nistelrooy and fellow assistant Rene Hake. There was a certain amount of relief in the celebrations after a bruising international break that has seen more speculation about his future. "The stats show we play good football but don\'t score enough," Ten Hag said. "Today, we scored two brilliant goals. The two goals we score are high quality. This team has the capacity to score very good goals and when you score and win you add some confidence. "The start of the season, we had some good performances. We had chances but didn\'t score enough and then everyone is negative. Today can help us, but it is only one win and we must build on this." And there lies the challenge for Ten Hag. Victory over Brentford will stop the questions about his position for a couple of days, but Fenerbahce and Jose Mourinho are waiting on Thursday in theUEFA Europa League. Only a consistent run of wins between now and the next international break will quiet the talk around whether he\'s the right man for the job. He can at least point to the development of Garnacho as one of the things he has got right at Old Trafford. Garnacho has needed Ten Hag to show enough faith to play him regularly since breaking into the first team during the former Ajax coach\'s first season in Manchester. Now it\'s Ten Hag who needs Garnacho to keep performing like he did against Brentford and keep the pressure off the manager\'s shoulders.'}},
 {'title': 'Latest scores',
  'summary': 'Results and scores from the Premier League, Champions League, La Liga, English football league and more.',
  'label': 'football',
  'full_link': 'https://www.espn.in/football/scoreboard',
  'scrappe_news2': None},
 {'title': "Rachin Ravindra headlines NZ's first Test win in India since 1988",
  'summary': 'Jasprit Bumrah threatened to take a wicket every second delivery, but NZ eased their way to the target of 107',
  'label': 'cricket',
  'full_link': 'https://www.espn.in/cricket/series/19430/report/1439896/day/5/india-vs-new-zealand-1st-test-icc-world-test-championship',
  'scrappe_news2': {'title': "Rachin Ravindra headlines NZ's first Test win in India since 1988",

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
from web_scraping_news import WebScrappingDataGeneration

In [8]:
url = ["https://www.espn.in/football/", "https://www.espn.in/cricket/", "https://www.espn.in/badminton/", "https://www.espn.in/"]
keywords = ["football", "soccer", "cricket", "badminton"]

for url_link in url:
    print(url_link)

    headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
        }     
     
    ## setup the beautiful soup functionality
    response = requests.get(url_link, headers=headers)
    print(response)
    bsoup = BeautifulSoup(response.content, 'html.parser')
    raw_links = bsoup.find_all("a")
    # print(raw_links)
    links = []
    text = []
    for link in raw_links:
        links.append(link.get("href"))
    #     text.append(link.string)
        
    print(links)

https://www.espn.in/football/
['#', '/', '#', '#', '#', '/olympics/', '/football/', '/cricket/', '/football/league/_/name/ind.1', '/f1/', '/nba/', '/badminton/', '/field-hockey/', '/tennis/', '#', '/wrestling/', '/rugby/', 'https://www.espn.in/football/league/_/name/fifa.world', '/mma/', '/boxing/', '/nfl/', '/nhl/', '/shooting/', '/athletics/', '/golf/', '/kabaddi/', '/wwe/', '/mlb/', '/chess/', '/motogp/', '/specialolympics/', '/mens-college-basketball/', '/racing/nascar/', '/college-football/', '/womens-basketball/', '/asian-games/', '/commonwealth-games/', 'http://xgames.com/', '/watch/', '/football/', '/football/', '/football/scoreboard', '/football/fixtures', '/soccer/table/_/league/eng.1', '/football/teams', '/football/competitions', '/football/transfers-news-and-features/', None, '#', '/espn/story/_/id/41831461/indian-sports-live-october-17-2024-schedule-news-updates-scores-results-commentary', '/espn/story/_/id/41812689/indian-sports-live-october-16-2024-schedule-news-updates-scores-results-commentary', '/football/story/_/id/41847318/premier-league-speeds-revealed-erling-haaland-fastest', '/football/story/_/id/41847542/emile-smith-rowe-had-leave-arsenal-happiness', '/football/story/_/id/41843315/england-thomas-tuchel-similar-sarina-wiegman-fa-chief', '/football/story/_/id/41835264/david-beckham-backs-jim-ratcliffe-man-united-change', '/football/story/_/id/41846167/spain-omit-ballon-dor-winner-bonmati-welfare-concerns', '/football/story/_/id/41845909/psg-probed-alleged-racial-profiling-recruitment', '/football/story/_/id/41827512/paul-pogba-considered-retiring-doping-reprieve', '/football/story/_/id/41844911/atletico-madrid-win-appeal-real-madrid-game-projectiles', '/football/story/_/id/41830928/england-manager-thomas-tuchel-bullish-2026-world-cup-aim', '/football/', '/football/', '/football/story/_/id/41809655/check-kylian-mbappe-real-madrid-manchester-united-erik-ten-hag-arne-slots-liverpool-hansi-flick-barcelona-vincent-kompany-bayern-munich', '/football/insider/story/_/id/41809892/20-years-lionel-messi-ranking-barcelona-psg-inter-miami-legends-seasons-worst-first', '/football/', '/football/', '/football/story/_/id/41827630/why-thomas-tuchel-england-manager-job-big-bet-gamble-analysis', '/football/story/_/id/41828467/thomas-tuchel-takes-england-job-lineker-neville-react', '/football/', '/football/', '/football/story/_/id/41827512/paul-pogba-considered-retiring-doping-reprieve', '/football/story/_/id/41836164/madrid-pursuit-alexander-arnold-heats-up', 'https://www.espn.co.uk/soccer/transfers', '/football/story/_/id/41838660/barcelona-unveil-coldplay-logo-clasico-kit-vs-real-madrid', '/football/', '/football/', '/football/story/_/id/41810455/psg-boss-luis-enrique-talks-mbappe-xavi-barcelona-new-doc', '/football/story/_/id/41769347/goals-not-enough-how-data-created-modern-striker', '/football/story/_/id/41791903/how-real-madrid-spain-reviving-art-long-range-shooting', '/football/story/_/id/41847318/premier-league-speeds-revealed-erling-haaland-fastest', '/football/story/_/id/41847542/emile-smith-rowe-had-leave-arsenal-happiness', '/football/story/_/id/41843315/england-thomas-tuchel-similar-sarina-wiegman-fa-chief', '/football/story/_/id/41835264/david-beckham-backs-jim-ratcliffe-man-united-change', '/football/story/_/id/41846167/spain-omit-ballon-dor-winner-bonmati-welfare-concerns', '/football/story/_/id/41845909/psg-probed-alleged-racial-profiling-recruitment', '/football/story/_/id/41827512/paul-pogba-considered-retiring-doping-reprieve', '/football/story/_/id/41844911/atletico-madrid-win-appeal-real-madrid-game-projectiles', '/football/story/_/id/41830928/england-manager-thomas-tuchel-bullish-2026-world-cup-aim', None, '#', 'http://www.espn.com/fantasy/', 'https://www.espn.in/football/scoreboard', 'https://www.espn.in/football/scoreboard', '/football/fixtures', '/football/fixtures', 'https://www.espn.in/football/table', 'https://www.espn.in/football/table', 'https://www.espn.in/football/transfers', 'https://www.espn.in/football/transfers', '/football/blog-espn-fc-united/story/4239858/fc-100-liverpoolbayern-dominateusmnt-stars-break-into-our-annual-ranking-of-soccers-best-players', '/football/blog-espn-fc-united/story/4239858/fc-100-liverpoolbayern-dominateusmnt-stars-break-into-our-annual-ranking-of-soccers-best-players', 'http://fantasyfc.espn.com/in/9/clienthome.do', 'http://fantasyfc.espn.com/in/9/clienthome.do', '/football/league/_/name/eng.1', '/football/league/_/name/uefa.champions', '/football/league/_/name/esp.1', 'https://global.espn.com/football/blog/transfer-talk/79/index', 'https://global.espn.com/football/blog/the-toe-poke/65/index', 'http://www.espn.com/espnradio/podcast/archive?id=10672984', 'http://www.espn.com/espnradio/podcast/archive/_/id/30162867', 'http://www.espn.com/espnradio/podcast/archive/_/id/26092845', 'https://andscape.com/', 'http://www.espn.com/espnw/', 'https://espndeportes.espn.com', 'http://www.espncricinfo.com', 'http://www.espn.com/espn/apps/download?app=espn', 'https://www.espn.com/espn/apps/fantasy', 'https://www.espn.com/espn/apps/download?app=tc', 'https://www.tiktok.com/@espnfc', 'https://www.instagram.com/espnfc/', 'https://x.com/ESPNFC', 'https://www.facebook.com/ESPNFC/', 'https://disneytermsofuse.com/english/', 'https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/', 'https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/addendum-to-the-global-privacy-policy/', 'http://preferences-mgr.truste.com/?type=espn&affiliateId=148']
https://www.espn.in/cricket/
['#', '/', '#', '#', '#', '/olympics/', '/football/', '/cricket/', '/football/league/_/name/ind.1', '/f1/', '/nba/', '/badminton/', '/field-hockey/', '/tennis/', '#', '/wrestling/', '/rugby/', 'https://www.espn.in/football/league/_/name/fifa.world', '/mma/', '/boxing/', '/nfl/', '/nhl/', '/shooting/', '/athletics/', '/golf/', '/kabaddi/', '/wwe/', '/mlb/', '/chess/', '/motogp/', '/specialolympics/', '/mens-college-basketball/', '/racing/nascar/', '/college-football/', '/womens-basketball/', '/asian-games/', '/commonwealth-games/', 'http://xgames.com/', '/watch/', '/cricket/', '/cricket/', '/cricket/series/_/id/8048/season/2024/indian-premier-league', '/cricket/scores', '/cricket/story/_/id/15508097/all-cricket-series-index', '/cricket/story/_/id/19644501/cricket-teams-list-espn', 'http://www.espncricinfo.com/rankings/content/page/211271.html', 'http://www.espncricinfo.com/ci/content/stats/index.html', None, '#', 'https://play.google.com/store/apps/details?id=com.july.cricinfo&hl=en', 'https://itunes.apple.com/in/app/espncricinfo-cricket/id417408017?mt=8', 'https://www.youtube.com/espncricinfo', 'https://www.facebook.com/Cricinfo/', 'https://twitter.com/espncricinfo', 'https://www.instagram.com/espncricinfo/', 'https://www.thecricketmonthly.com', 'https://www.espn.in', '/cricket/series/22709/game/1439896/india-vs-new-zealand-1st-test-new-zealand-in-india-2024-25', '/cricket/', '/cricket/', '/cricket/story/_/id/41845652/shakib-final-test-cloud-due-protests-dhaka', '/cricket/story/_/id/41846579/rishabh-pant-suffers-blow-knee-goes-field-first-test-new-zealand', '/cricket/story/_/id/41847560/india-vs-nz-rohit-sharma-hurting-misjudging-bengaluru-pitch', '/cricket/story/_/id/41848321/pak-vs-eng-salman-agha-pakistan-win-massive-horror-run', '/cricket/story/_/id/41848116/richa-ghosh-misses-nz-odis-sit-board-exams', '/cricket/story/_/id/41848310/bcb-terminates-chandika-hathurusinghe-bangladesh-head-coach', '/cricket/story/_/id/41843710/ipl-2025-badani-take-dc-head-coach', 'https://www.espn.in/cricket/team/_/id/7/pakistan', 'https://www.espn.in/cricket/team/_/id/7/pakistan', '/cricket/story/_/id/41847818/pak-vs-eng-england-let-small-things-slip-big-task-looms-them', '/cricket/story/_/id/41845652/shakib-final-test-cloud-due-protests-dhaka', '/cricket/story/_/id/41846579/rishabh-pant-suffers-blow-knee-goes-field-first-test-new-zealand', '/cricket/story/_/id/41847560/india-vs-nz-rohit-sharma-hurting-misjudging-bengaluru-pitch', '/cricket/story/_/id/41848321/pak-vs-eng-salman-agha-pakistan-win-massive-horror-run', '/cricket/story/_/id/41848116/richa-ghosh-misses-nz-odis-sit-board-exams', '/cricket/story/_/id/41848310/bcb-terminates-chandika-hathurusinghe-bangladesh-head-coach', '/cricket/story/_/id/41843710/ipl-2025-badani-take-dc-head-coach', None, '#', 'http://www.espn.com/fantasy/', 'https://play.google.com/store/apps/details?id=com.july.cricinfo&hl=en', 'https://itunes.apple.com/in/app/espncricinfo-cricket/id417408017?mt=8', 'https://www.youtube.com/espncricinfo', 'https://www.facebook.com/Cricinfo/', 'https://twitter.com/espncricinfo', 'https://www.instagram.com/espncricinfo/', 'https://www.thecricketmonthly.com', 'https://www.espn.in', 'https://disneytermsofuse.com/english/', 'https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/', 'https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/addendum-to-the-global-privacy-policy/', 'http://preferences-mgr.truste.com/?type=espn&affiliateId=148']
https://www.espn.in/badminton/
['#', '/', '#', '#', '#', '/olympics/', '/football/', '/cricket/', '/football/league/_/name/ind.1', '/f1/', '/nba/', '/badminton/', '/field-hockey/', '/tennis/', '#', '/wrestling/', '/rugby/', 'https://www.espn.in/football/league/_/name/fifa.world', '/mma/', '/boxing/', '/nfl/', '/nhl/', '/shooting/', '/athletics/', '/golf/', '/kabaddi/', '/wwe/', '/mlb/', '/chess/', '/motogp/', '/specialolympics/', '/mens-college-basketball/', '/racing/nascar/', '/college-football/', '/womens-basketball/', '/asian-games/', '/commonwealth-games/', 'http://xgames.com/', '/watch/', '/badminton/', '/badminton/', None, '#', '/badminton/story/_/id/41660332/bwf-arctic-open-pv-sindhu-lakshya-sen-return-bwf-world-tour', '/olympics/story/_/id/40734600/lakshya-fails-paris-olympics-2024-pressure-test-tweaks-smoother-road-ahead', '/olympics/story/_/id/40732506/lee-zii-jia-claims-first-olympic-medal-malaysia-another-comeback-paris', '/olympics/story/_/id/40730664/taiwan-wants-sign-incident-olympic-badminton-investigated', '/olympics/story/_/id/40724728/taiwan-duo-defends-badminton-men-doubles-gold-olympics', '/olympics/story/_/id/40723838/aaron-chia-soh-wooi-yik-produce-incredible-rally-reclaim-olympic-badminton-mens-doubles-bronze', '/olympics/story/_/id/40723228/lakshya-sen-lee-zii-jia-paris-olympics-2024-bronze-medal-india-malaysia', '/olympics/story/_/id/40722189/lovlina-borgohain-exits-paris-olympics-quarters-li-qian', '/olympics/story/_/id/40715683/japan-pip-malaysia-olympic-badminton-womens-doubles-bronze-medal', '/olympics/story/_/id/40713852/lakshya-sen-viktor-axelsen-india-paris-olympics-2024-medal-semifinal', '/olympics/story/_/id/40710146/lee-zii-jia-advances-loh-kean-yew-falls-short-olympic-badminton-quarterfinals', '/olympics/story/_/id/40708821/olympics-paris-2024-india-lakshya-sen-history-chou-tien-chen', '/olympics/story/_/id/40704001/olympics-paris-2024-india-pv-sindhu-dilemma-cupboard-full-there-boxes-unticked', '/olympics/story/_/id/40700786/loh-kean-yew-advances-olympic-badminton-quarterfinals-yeo-jia-min-valiant-defeat', '/olympics/story/_/id/40700217/pv-sindhu-exits-paris-olympics-pre-quarters-bingjiao', '/olympics/story/_/id/40699084/lakshya-enters-paris-olympics-quarterfinals-draw-form-side', '/olympics/story/_/id/40698070/india-paris-2024-satwik-rankireddy-chirag-shetty-crash-olympics-quarters-malaysian-masterclass', '/olympics/story/_/id/40695287/hs-prannoy-vs-lakshya-sen-india-paris-olympics-2024-study-contrasts', '/olympics/story/_/id/40690045/india-paris-olympics-2024-badminton-stars-sindhu-satwik-chirag-lakshya-hs-prannoy-path-medal', '/olympics/story/_/id/40688362/underdog-lakshya-sen-overcomes-medal-favourite-commanding-win-jonatan-christie', '/olympics/story/_/id/40687853/yeo-jia-min-first-singaporean-reach-olympic-badminton-knockout-stage-2012', 'http://espn.com/video/clip?id=16972496', '/video/clip?id=16972496', '/badminton/story/_/id/15473997/olympic-medal-bigger-wc-medals-sindhu', '/badminton/story/_/id/15473997/olympic-medal-bigger-wc-medals-sindhu', '/football/club/manchester-united/360/blog/post/2876904/manchester-united-matches-under-louis-van-gaal-that-led-to-dutchmans-doom', '/football/club/manchester-united/360/blog/post/2876904/manchester-united-matches-under-louis-van-gaal-that-led-to-dutchmans-doom', 'http://www.espn.com/espnw/voices/article/15562343/the-athleticism-beyonce', 'http://www.espn.com/espnw/voices/article/15562343/the-athleticism-beyonce', '/cricket/story/_/id/15559699/was-tony-cozier-last-golden-age-commentators', '/cricket/story/_/id/15559699/was-tony-cozier-last-golden-age-commentators', None, '#', 'http://www.espn.com/fantasy/', 'https://disneytermsofuse.com/english/', 'https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/', 'https://privacy.thewaltdisneycompany.com/en/current-privacy-policy/addendum-to-the-global-privacy-policy/', 'http://preferences-mgr.truste.com/?type=espn&affiliateId=148']
https://www.espn.in/

In [9]:

# Function to extract news articles from a page
def scrape_news_from_page(url, label):
    # Send a request to the website
    headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
        }  
    
    response = requests.get(url, headers=headers)
        
    # Check if request was successful
    if response.status_code != 200:
        print(f"Failed to retrieve page: {url}")
        return []

    # Parse the page content
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find all the articles or news elements (modify selectors based on website structure)
    news_items = soup.find_all('article')  # or use specific class or tag based on website

    # List to store scraped news data
    news_data = []

    # Loop through the found news items and extract relevant data
    for item in news_items:
        try:
            # Extract title, link, and summary (modify selectors as needed)
            title = item.find('h2').get_text().strip() if item.find('h2') else "No title"
            link = item.find('a')['href'] if item.find('a') else "No link"
            summary = item.find('p').get_text().strip() if item.find('p') else "No summary"

            # Append the news item to the list
            news_data.append({
                'title': title,
                'link': link,
                'summary': summary,
                'label': label,
                'raw_url': url
            })
        except Exception as e:
            print(f"Error processing article: {e}")

    return pd.DataFrame(news_data)

In [10]:
# scrape_news_from_page("https://www.espn.in/football/")
urls_with_label = [
    {"url": "https://www.espn.in/football/", "label": "football"},
    {"url": "https://www.espn.in/cricket/", "label": "cricket"},
    {"url": "https://www.espn.in/badminton/", "label": "badminton"},
    {"url": "https://www.espn.in/", "label": "general"}
    ]

all_news_df = pd.DataFrame()

# Loop over each URL and scrape the data
for item in urls_with_label:
    url = item["url"]
    label = item["label"]
    
    print(f"Scraping: {url}")
    news_df = scrape_news_from_page(url, label=label)  # Scrape the current URL
    all_news_df = pd.concat([all_news_df, news_df], ignore_index=True)

Scraping: https://www.espn.in/football/
Error processing article: 'href'
Scraping: https://www.espn.in/cricket/
Error processing article: 'href'
Scraping: https://www.espn.in/badminton/
Error processing article: 'href'
Scraping: https://www.espn.in/
Error processing article: 'href'

In [20]:
from urllib.parse import urljoin

filtered_news_df = all_news_df[all_news_df['summary'] != "No summary"].reset_index().drop("index", axis=1)

def complete_link(row):
    if row['link'].startswith('/'):  # Check if it's a relative URL
        return urljoin(row['raw_url'], row['link'])  # Join base URL and relative link
    else:
        return row['link'] 
    
filtered_news_df["full_link"] = filtered_news_df.apply(complete_link, axis = 1)
required_df = filtered_news_df.drop(["link", "raw_url"], axis=1)

In [22]:
required_df = filtered_news_df.drop(["link", "raw_url"], axis=1)

In [28]:
filtered_req_df = required_df[required_df["full_link"] != "No link"].reset_index()

from llm_newsScraping import create_scraped_news

# filtered_req_df["scrapped_news"] = filtered_req_df["full_link"].apply(create_scraped_news)

In [30]:
def create_scraped_news_with_error_handling(link):
    try:
        # Call your original scraping function (or LLM call)
        return create_scraped_news(link)  # Assuming this is your existing function
    except Exception as e:  # Catch any type of error
        print(f"Error for link {link}: {e}")
        return None  # Return None if any error occurs

# Apply the modified function with error handling
filtered_req_df["scrapped_news"] = filtered_req_df["full_link"].apply(create_scraped_news_with_error_handling)

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Error for link https://www.espn.in/football/scoreboard: Error code: 400 - {'error': {'message': 'Please reduce the length of the messages or completion.', 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [32]:
filtered_req_df["scrapped_news"][1]

"## ESPN India Edition Menu\n\nThe ESPN India Edition menu provides access to a variety of sports news, live events, and analysis. \n\n**Main Features:**\n\n* **Scores:** Latest scores and results from various leagues and sports.\n* **Live Transfer Talk:** Up-to-date information on player transfers and rumors.\n* **Match Previews and Recaps:** Detailed analysis and highlights of recent games.\n* **Player and Team Ratings:** Expert opinions on individual players and team performances.\n* **News and Features:** Exclusive articles, interviews, and analysis from industry experts.\n* **Preseason Plans:** Insights into how teams are preparing for the upcoming season.\n\n**Specific Content:**\n\n* **Arsenal Lose First Game of Season:** Detailed report on Arsenal's 2-0 defeat to Bournemouth, including player ratings and manager analysis.\n* **Transfer Talk:** Latest rumors and updates on player movements.\n* **Manchester United Comeback:** Article discussing the unlikely victory for Manchester United against Everton.\n\n**Additional Options:**\n\n* **Email and Print options:** Receive updates and access content via email or print.\n* **Related articles:** Related news and stories based on your interests.\n\n**Overall, the ESPN India Edition menu offers a comprehensive and user-friendly experience for sports fans, providing access to the latest news, analysis, and highlights from the world of sports.**"

In [40]:
filtered_req_df.drop("index", axis=1)

,title,summary,label,full_link,scrapped_news
0,"Liverpool vs Chelsea preview: How to watch, st...",Everything you need to know as Liverpool host ...,football,https://www.espn.in/football/story/_/id/418469...,## ESPN India Edition - Liverpool vs Chelsea P...
1,Player ratings: Arsenal suffer first loss of s...,Arsenal suffered their first loss of the 2024-...,football,https://www.espn.in/football/story/_/id/418862...,## ESPN India Edition Menu\n\nThe ESPN India E...
2,"Bloodied but not beaten, Man United comeback s...",Man United came from behind to win against Bre...,football,https://www.espn.in/football/story/_/id/418840...,## ESPN India Edition: Menu\n\nThe provided te...
3,Latest scores,"Results and scores from the Premier League, Ch...",football,https://www.espn.in/football/scoreboard,None
4,Rachin Ravindra headlines NZ's first Test win ...,Jasprit Bumrah threatened to take a wicket eve...,cricket,https://www.espn.in/cricket/series/19430/repor...,## ESPN India Edition: Live Cricket Score & Hi...
5,Cricket,"""Hope it can be an even better day for New Zea...",cricket,https://www.espn.in/cricket/,## ESPN India Edition Website Menu Description...
6,New Zealand,New Zealand captain on the importance of the w...,cricket,https://www.espn.in/cricket/team/_/id/5/new-ze...,## ESPN India Edition: Menu\n\n**Content:**\n\...
7,India,Rohit Sharma looks back at India's eight-wicke...,cricket,https://www.espn.in/cricket/team/_/id/6/india,## ESPN India Edition: Menu\n\nThe provided te...
8,"Arctic Open: All eyes on Sindhu, Lakshya in re...",PV Sindhu and Lakshya Sen will be back on the ...,badminton,https://www.espn.in/badminton/story/_/id/41660...,## ESPN India Edition Menu\n\nThe provided tex...
9,news - in badminton,Lakshya Sen's debut Olympics journey came to a...,badminton,https://www.espn.in/olympics/story/_/id/407346...,## ESPN India Edition: Menu\n\nThe provided te...
10,News,Taiwan's government on Monday called on French...,badminton,https://www.espn.in/olympics/story/_/id/407306...,## ESPN India Edition Menu\n\nThe ESPN India E...
11,News,Taiwan's Lee Yang and Wang Chi-Lin retained th...,badminton,https://www.espn.in/olympics/story/_/id/407247...,## ESPN India Edition Menu\n\nThe ESPN India E...
12,news - in badminton,Malaysia's Aaron Chia and Soh Wooi Yik have re...,badminton,https://www.espn.in/olympics/story/_/id/407238...,## ESPN India Edition - Menu\n\nThe ESPN India...
13,news - in badminton,"Simply put, Lakshya has a great chance to win ...",badminton,https://www.espn.in/olympics/story/_/id/407232...,## Summary of ESPN article: Lakshya Sen vs Lee...
14,news - in badminton,Lovlina just couldn't find her best when she n...,badminton,https://www.espn.in/olympics/story/_/id/407221...,## ESPN India Edition - Menu\n\nThe ESPN India...
15,news - in badminton,Chiharu Shida and Nami Matsuyama claimed Japan...,badminton,https://www.espn.in/olympics/story/_/id/407156...,## ESPN India Edition Menu\n\nThe ESPN India E...
16,news - in badminton,It won't be easy for Lakshya. Axelsen is prett...,badminton,https://www.espn.in/olympics/story/_/id/407138...,## ESPN India Edition Menu\n\nThe provided tex...
17,news - in badminton,Lee Zii Jia remains firmly in the hunt for a m...,badminton,https://www.espn.in/olympics/story/_/id/407101...,## ESPN India Edition - Menu Description\n\nTh...
18,news - in badminton,Lakshya Sen is the first Indian man to reach a...,badminton,https://www.espn.in/olympics/story/_/id/407088...,## ESPN India Edition - Menu Description\n\nTh...
19,news - in badminton,Sindhu's exit from the Paris Olympics leaves h...,badminton,https://www.espn.in/olympics/story/_/id/407040...,## ESPN India Edition - Menu\n\nThe provided t...
20,news - in badminton,It was a mixed day for Singapore in Olympics b...,badminton,https://www.espn.in/olympics/story/_/id/407007...,## ESPN India Edition - Menu\n\nThe ESPN India...
21,news - in badminton,Sen is now only the third Indian to reach the ...,badminton,https://www.espn.in/olympics/story/_/id/407002...,## ESPN India Edition - Menu\n\nThe ESPN India...
22,news - in badminton,Sen is now only the third Indian to reach the ...,badminton,https://www.espn.in/olympics/story/_/id/406990...,## ESPN India Edition - Menu\n\nThe provided t...
23,news - in badminton,Satwiksairaj Rankireddy and Chirag Shetty lost...,badminton,https://www.espn.in/olympics/story/_/id/406980...,## ESPN India Edition Menu\n\nThe provided tex...
24,news - in badminton,Lakshya Sen vs HS Prannoy will see an all-Indi...,badminton,https://www.espn.in/olympics/story/_/id/406952...,## ESPN India Edition - Menu\n\nThe ESPN India...
25,Summer Olympics,Four Indians are in contention for three medal...,badminton,https://www.espn.in/olympics/story/_/id/406900...,## ESPN India Edition - Menu Description\n\nTh...
26,Summer Olympics,Lakshya put on a masterclass of creative defen...,badminton,https://www.espn.in/olympics/story/_/id/406883...,**ESPN India Edition Website Menu**\n\nThe ESP...
27,Olympic Sports,Yeo Jia Min has ended a 12-year wait for Singa...,badminton,https://www.espn.in/olympics/story/_/id/406878...,## ESPN India Edition Menu\n\nThe ESPN India E...
28,Moment 3. Padukone wins the All England Open,Top 20 moments in Indian sports,badminton,http://espn.com/video/clip?id=16972496,## ESPN India Edition - Menu\n\n**Main Menu:**...
29,'Olympic medal will be bigger than WC medals' ...,World No. 10 PV Sindhu expressed her happiness...,badminton,https://www.espn.in/badminton/story/_/id/15473...,## ESPN India Edition Menu\n\nThe ESPN India E...
30,Eight matches that doomed Louis van Gaal at Ma...,John Brewin reviews the eight matches that ult...,badminton,https://www.espn.in/football/club/manchester-u...,## ESPN India Edition - Menu\n\n**Main Content...
31,ESPNW - Voices,"Is Beyonce an athlete, too? Joy Priest explore...",badminton,http://www.espn.com/espnw/voices/article/15562...,## ESPN Menu Description\n\nThe provided text ...
32,Was Cozier the last of a golden age of comment...,The sport and media landscape has changed so m...,badminton,https://www.espn.in/cricket/story/_/id/1555969...,## ESPN India Edition - Menu\n\nThe provided t...
33,"Liverpool vs Chelsea preview: How to watch, st...",Everything you need to know as Liverpool host ...,general,https://www.espn.in/football/story/_/id/418469...,## ESPN India Edition - Liverpool vs Chelsea P...
34,Rachin Ravindra headlines NZ's first Test win ...,Jasprit Bumrah threatened to take a wicket eve...,general,https://www.espn.in/cricket/series/19430/repor...,**ESPN India Edition - Match Summary**\n\nThe ...
35,Player ratings: Arsenal suffer first loss of s...,Arsenal suffered their first loss of the 2024-...,general,https://www.espn.in/football/story/_/id/418862...,## ESPN India Edition - Menu Description\n\nTh...
36,"Bloodied but not beaten, Man United comeback s...",Man United came from behind to win against Bre...,general,https://www.espn.in/football/story/_/id/418840...,## ESPN India Edition Menu\n\nThe provided tex...
37,"Pro Kabaddi League 2024-25: PKL 11 News, Sched...","PKL 11: Check all the latest scores, results, ...",general,https://www.espn.in/kabaddi/story/_/id/4184292...,## ESPN India Edition - Pro Kabaddi League Cov...

In [55]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Function to scrape the description from a single URL
def scrape_description(link):
    try:
        # Make a request to the webpage
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
        } 
        response = requests.get(link, headers=headers, timeout=5)
        if response.status_code != 200:
            return None  # Return None if the response is not OK

        # Parse the HTML content
        soup = BeautifulSoup(response.content, 'html.parser')

        # Try to extract the description from the meta tag
        description = soup.find('meta', attrs={'name': 'article'})
        if description and description.get('content'):
            return description['content'].strip()  # Return the description if found

        # Fallback: look for the first few paragraph tags
        paragraphs = soup.find_all('p')
        if paragraphs:
            return ' '.join([p.get_text().strip() for p in paragraphs[:3]])  # Return first 3 paragraphs

        return None  # Return None if no meaningful content found

    except Exception as e:
        print(f"Error scraping {link}: {e}")
        return None

# List of URLs to scrape
# urls = [
#     'https://www.goal.com/en/news/arsenal-player-ratings/1idjxgqwqer6u1dfgh2fkt',
#     'https://www.espncricinfo.com/story/kohli-wins-world-cup-2023'
# ]

# # Create a DataFrame from the list of URLs
# df = pd.DataFrame(urls, columns=['full_link'])

# # Scrape descriptions for each URL and add to the DataFrame
# df['description'] = df['full_link'].apply(scrape_description)

# # Display the DataFrame with descriptions
# print(df)

In [70]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Function to scrape meaningful content from the specified structure
def scrape_article(link):
    try:
        # Send a GET request to the URL
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
        } 
        response = requests.get(link, headers=headers)
        response.raise_for_status()  # Raise an error for bad responses

        # Parse the page content
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the article container
        article = soup.find('article', class_='article')
        if article:
            # Extract the header content (title, etc.)
            header = article.find('header', class_='article-header')
            title = header.get_text(strip=True) if header else 'No Title'

            # Extract the main body content
            body = article.find('div', class_='article-body')
            paragraphs = body.find_all('p') if body else []
            body_content = " ".join(paragraph.get_text(strip=True) for paragraph in paragraphs)

            return {
                'title': title,
                'content': body_content.strip()  # Return the text content
            }
        return None  # Return None if no content is found

    except Exception as e:
        print(f"Error scraping {link}: {e}")
        return None

In [71]:
scrape_article(filtered_req_df["full_link"][1])

{'title': 'Arsenal ratings: First loss of season due to Saliba, Trossard',
 'content': 'Arsenalsuffered their first loss of the season on Saturday as they fell 2-0 toBournemouthat the Vitality Stadium. The Gunners had control of the game until the 30th minute, whenLeandro Trossard\'s careless pass leftWilliam Salibain trouble before earning red for a foul that VAR deemed to have deniedEvanilsona clear goal-scoring opportunity. Some positive moments of goalkeeping byDavid Rayaensured Arsenal held Bournemouth scoreless by the break. Antoine Semenyowas one of Bournemouth\'s brightest as the Cherries began to create chances, though he should have done better moments after the restart with an effort at the backpost that was struck off target. Arsenal could have taken the lead with their best chance of the match whenMikel MerinointerceptedKepa Arrizabalaga\'s pass before picking out substituteGabriel Martinelli, only for him to strike the ball straight at the goalkeeper. That miss proved to be costly as they went behind two minutes later, withRyan Christiefinishing off a well-taken Bournemouth corner. An under-hit pass byJakub Kiwiorled to Raya giving away a penalty for the home side to double the lead throughJustin Kluivert, and the Gunners looked resigned to defeat with Mikel Merino being withdrawn. Merino enjoyed a bright performance despite the result, and he looks to be a strong fit for Arsenal\'s system.Declan Ricewas also a standout in midfield with his defensive work. The absences of Martin Ødegaard andBukayo Sakawere noticeable in an Arsenal attack that didn\'t create many moments of promise. An upcoming suspension for William Saliba means he misses the nextPremier Leaguematch againstLiverpool. Mikel Arteta, 6 --There was little Arteta could do after individual errors were punished, but he could have seen his side go 1-0 up on another day if substitute Gabriel Martinelli converted his chance. GKDavid Raya, 5 --Raya looked uncertain when claiming crosses and he also played a misplaced ball straight to Alex Scott in the first half. While he made some saves to keep the game at 0-0, an overall inconsistent evening was compounded when he gave away a penalty. DFGabriel Magalhães, 6-- Gabriel cleared the danger on a number of occasions and registered a couple of blocks. Not as effective as usual from attacking set-pieces. DFWilliam Saliba, 4-- Saliba looked in control before he was sent off following a VAR review after he pulled down Evanilson to deny a goal-scoring opportunity. There was some distance to go, which could see the France international regret not using his pace rather than fouling. DFRiccardo Calafiori, 6-- Left Antoine Semenyo at the backpost moments into the second half, but was let off by a poor finish by the Bournemouth forward. His efforts helped create some half-chances at times when driving with the ball into midfield. DFBen White, 5-- Beaten too easily at times and picked up a booking for timewasting with the score at 0-0. MFMikel Merino, 7-- The Spain international was composed in possession, particularly in advanced areas, and he enjoyed some positive link-up play with Raheem Sterling before he was taken off after the red card. Took up intelligent positions to cut off passing lanes in the middle of the pitch, and created Arsenal\'s best chance when playing in Gabriel Martinelli following a well-timed interception on Kepa Arrizabalaga\'s pass. MFDeclan Rice, 7-- Rice provided a strong anchor when Arsenal were looking to defend with 10 men, where he regularly anticipated play to clear the danger. Worked hard to make up for the numbers advantage, and tried to progress the ball into advanced areas. MFThomas Partey, 6-- Progressed the ball impressively through the lines from defensive midfield, and also chose the right moments to drop into centre-back to create a back-three. Little he could do about either of the goals. FWKai Havertz, 6-- Havertz worked hard and tried to make things happen with minimal service, with positive runs directly at the defence that led to some half-chances. FWLeandro Trossard, 5-- Trossard\'s poor pass to Saliba led to the red card that made the game much more difficult for the Gunners. Ineffective overall, and replaced by Gabriel Martinelli in the 64th minute. FWRaheem Sterling, 5-- Stayed wide to stretch the pitch and had one moment during which he tried to cut inside and beat his marker, but didn\'t have enough opportunities to make an impact on the game. Replaced for tactical reasons after Saliba\'s red card. Jakub Kiwior(Sterling, 37"), 4 --A match to forget for Kiwior, who struggled early on with the pace of Semenyo, and after he under-hit his pass to Raya before Bournemouth\'s penalty, he was taken back off the pitch by Arteta. He was not the solution Arteta had hoped for. Gabriel Martinelli(Trossard, 64"), 5 --It didn\'t take long for Martinelli to get involved with Arsenal\'s best chance of the game five minutes after coming in, but he should have done better with the finish that was straight at Arrizabalaga. Gabriel Jesus(Kiwior, 81"), N/R-- Positive in possession and tried to make something happen by going alone with a dribbling run through the Bournemouth defence before he was eased off the ball. Ethan Nwaneri(Merino, 81") N/R-- Introduced for Merino butArsenalcouldn\'t garner any control of the game to begin a late comeback.'}

In [56]:
scrape_description(filtered_news_df["full_link"][1])

"Welcome to ESPN India Edition Janusz Michallik and Luis Miguel Echegaray criticise Mikel Arteta's tactical decisions after William Saliba's red card in the defeat to Bournemouth. (2:06) Arsenal suffered their first loss of the season on Saturday as they fell 2-0 to Bournemouth at the Vitality Stadium."

In [72]:
filtered_req_df["scrappe_news2"] = filtered_req_df["full_link"].apply(scrape_article)

In [73]:
filtered_req_df

,index,title,summary,label,full_link,scrapped_news,scrapped_news1,scrappe_news2
0,0,"Liverpool vs Chelsea preview: How to watch, st...",Everything you need to know as Liverpool host ...,football,https://www.espn.in/football/story/_/id/418469...,## ESPN India Edition - Liverpool vs Chelsea P...,Everything you need to know as Liverpool host ...,{'title': 'Liverpool vs Chelsea preview: How t...
1,1,Player ratings: Arsenal suffer first loss of s...,Arsenal suffered their first loss of the 2024-...,football,https://www.espn.in/football/story/_/id/418862...,## ESPN India Edition Menu\n\nThe ESPN India E...,Arsenal suffered their first loss of the 2024-...,{'title': 'Arsenal ratings: First loss of seas...
2,2,"Bloodied but not beaten, Man United comeback s...",Man United came from behind to win against Bre...,football,https://www.espn.in/football/story/_/id/418840...,## ESPN India Edition: Menu\n\nThe provided te...,Man United came from behind to win against Bre...,{'title': 'Man United comeback shows they must...
3,3,Latest scores,"Results and scores from the Premier League, Ch...",football,https://www.espn.in/football/scoreboard,None,Live scores for all soccer major league games ...,None
4,4,Rachin Ravindra headlines NZ's first Test win ...,Jasprit Bumrah threatened to take a wicket eve...,cricket,https://www.espn.in/cricket/series/19430/repor...,## ESPN India Edition: Live Cricket Score & Hi...,Read the detailed Reports & Articles of India ...,{'title': 'Rachin Ravindra headlines NZ's firs...
5,5,Cricket,"""Hope it can be an even better day for New Zea...",cricket,https://www.espn.in/cricket/,## ESPN India Edition Website Menu Description...,"Get cricket scores, schedules, match commentar...",None
6,6,New Zealand,New Zealand captain on the importance of the w...,cricket,https://www.espn.in/cricket/team/_/id/5/new-ze...,## ESPN India Edition: Menu\n\n**Content:**\n\...,Read about New Zealand Cricket Team latest Sco...,None
7,7,India,Rohit Sharma looks back at India's eight-wicke...,cricket,https://www.espn.in/cricket/team/_/id/6/india,## ESPN India Edition: Menu\n\nThe provided te...,"Read about India Cricket Team latest Scores, N...",None
8,8,"Arctic Open: All eyes on Sindhu, Lakshya in re...",PV Sindhu and Lakshya Sen will be back on the ...,badminton,https://www.espn.in/badminton/story/_/id/41660...,## ESPN India Edition Menu\n\nThe provided tex...,PV Sindhu and Lakshya Sen will be back on the ...,"{'title': 'Arctic Open: All eyes on Sindhu, La..."
9,9,news - in badminton,Lakshya Sen's debut Olympics journey came to a...,badminton,https://www.espn.in/olympics/story/_/id/407346...,## ESPN India Edition: Menu\n\nThe provided te...,Lakshya Sen's debut Olympics journey came to a...,{'title': 'Lakshya fails Paris pressure test b...
10,11,News,Taiwan's government on Monday called on French...,badminton,https://www.espn.in/olympics/story/_/id/407306...,## ESPN India Edition Menu\n\nThe ESPN India E...,Taiwan's government on Monday called on French...,{'title': 'Taiwan wants sign incident at Olymp...
11,12,News,Taiwan's Lee Yang and Wang Chi-Lin retained th...,badminton,https://www.espn.in/olympics/story/_/id/407247...,## ESPN India Edition Menu\n\nThe ESPN India E...,Taiwan's Lee Yang and Wang Chi-Lin retained th...,{'title': 'Taiwan duo defends badminton men's ...
12,13,news - in badminton,Malaysia's Aaron Chia and Soh Wooi Yik have re...,badminton,https://www.espn.in/olympics/story/_/id/407238...,## ESPN India Edition - Menu\n\nThe ESPN India...,Malaysia's Aaron Chia and Soh Wooi Yik have re...,"{'title': 'Aaron Chia, Soh Wooi Yik produce in..."
13,14,news - in badminton,"Simply put, Lakshya has a great chance to win ...",badminton,https://www.espn.in/olympics/story/_/id/407232...,## Summary of ESPN article: Lakshya Sen vs Lee...,"Simply put, Lakshya has a great chance to win ...",{'title': 'Lakshya Sen vs Lee Zii Jia at Paris...
14,15,news - in badminton,Lovlina just couldn't find her best when she n...,badminton,https://www.espn.in/olympics/story/_/id/407221...,## ESPN India Edition - Menu\n\nThe ESPN India...,Lovlina just couldn't find her best when she n...,{'title': 'Lovlina Borgohain exits Paris Olymp...
15,16,news - in badminton,Chiharu Shida and Nami Matsuyama claimed Japan...,badminton,https://www.espn.in/olympics/story/_/id/407156...,## ESPN India Edition Menu\n\nThe ESPN India E...,Chiharu Shida and Nami Matsuyama claimed Japan...,{'title': 'Japan pip Malaysia to Olympic badmi...
16,17,news - in badminton,It won't be easy for Lakshya. Axelsen is prett...,badminton,https://www.espn.in/olympics/story/_/id/407138...,## ESPN India Edition Menu\n\nThe provided tex...,It won't be easy for Lakshya. Axelsen is prett...,{'title': 'Lakshya Sen vs Viktor Axelsen at Pa...
17,18,news - in badminton,Lee Zii Jia remains firmly in the hunt for a m...,badminton,https://www.espn.in/olympics/story/_/id/407101...,## ESPN India Edition - Menu Description\n\nTh...,Lee Zii Jia remains firmly in the hunt for a m...,"{'title': 'Lee Zii Jia advances, Loh Kean Yew ..."
18,19,news - in badminton,Lakshya Sen is the first Indian man to reach a...,badminton,https://www.espn.in/olympics/story/_/id/407088...,## ESPN India Edition - Menu Description\n\nTh...,Lakshya Sen is the first Indian man to reach a...,{'title': 'Lakshya Sen makes history after stu...
19,21,news - in badminton,Sindhu's exit from the Paris Olympics leaves h...,badminton,https://www.espn.in/olympics/story/_/id/407040...,## ESPN India Edition - Menu\n\nThe provided t...,Sindhu's exit from the Paris Olympics leaves h...,{'title': 'Sindhu's dilemma: Her cupboard is f...
20,22,news - in badminton,It was a mixed day for Singapore in Olympics b...,badminton,https://www.espn.in/olympics/story/_/id/407007...,## ESPN India Edition - Menu\n\nThe ESPN India...,It was a mixed day for Singapore in Olympics b...,{'title': 'Loh Kean Yew advances to Olympic ba...
21,23,news - in badminton,Sen is now only the third Indian to reach the ...,badminton,https://www.espn.in/olympics/story/_/id/407002...,## ESPN India Edition - Menu\n\nThe ESPN India...,Sen is now only the third Indian to reach the ...,{'title': 'PV Sindhu exits Paris Olympics in p...
22,25,news - in badminton,Sen is now only the third Indian to reach the ...,badminton,https://www.espn.in/olympics/story/_/id/406990...,## ESPN India Edition - Menu\n\nThe provided t...,Sen is now only the third Indian to reach the ...,{'title': 'Lakshya enters Paris Olympics quart...
23,27,news - in badminton,Satwiksairaj Rankireddy and Chirag Shetty lost...,badminton,https://www.espn.in/olympics/story/_/id/406980...,## ESPN India Edition Menu\n\nThe provided tex...,Satwiksairaj Rankireddy and Chirag Shetty lost...,{'title': 'Sat-Chi crash out in Olympics quart...
24,28,news - in badminton,Lakshya Sen vs HS Prannoy will see an all-Indi...,badminton,https://www.espn.in/olympics/story/_/id/406952...,## ESPN India Edition - Menu\n\nThe ESPN India...,Lakshya Sen vs HS Prannoy will see an all-Indi...,{'title': 'HS Prannoy vs Lakshya Sen at Paris ...
25,29,Summer Olympics,Four Indians are in contention for three medal...,badminton,https://www.espn.in/olympics/story/_/id/406900...,## ESPN India Edition - Menu Description\n\nTh...,Four Indians are in contention for three medal...,{'title': 'Olympics: Indian Badminton stars Si...
26,30,Summer Olympics,Lakshya put on a masterclass of creative defen...,badminton,https://www.espn.in/olympics/story/_/id/406883...,**ESPN India Edition Website Menu**\n\nThe ESP...,Lakshya put on a masterclass of creative defen...,{'title': ''Underdog' Lakshya Sen overcomes me...
27,31,Olympic Sports,Yeo Jia Min has ended a 12-year wait for Singa...,badminton,https://www.espn.in/olympics/story/_/id/406878...,## ESPN India Edition Menu\n\nThe ESPN India E...,Yeo Jia Min has ended a 12-year wait for Singa...,{'title': 'Yeo Jia Min first Singaporean to re...
28,32,Moment 3. Padukone wins the All England Open,Top 20 moments in Indian sports,badminton,http://espn.com/video/clip?id=16972496,## ESPN India Edition - Menu\n\n**Main Menu:**...,Top 20 moments in Indian sports,None
29,33,'Olympic medal will be bigger than WC medals' ...,World No. 10 PV Sindhu expressed her happiness...,badminton,https://www.espn.in/badminton/story/_/id/15473...,## ESPN India Edition Menu\n\nThe ESPN India E...,World No. 10 PV Sindhu expressed her happiness...,{'title': ''Olympic medal will be bigger than ...
30,34,Eight matches that doomed Louis van Gaal at Ma...,John Brewin reviews the eight matches that ult...,badminton,https://www.espn.in/football/club/manchester-u...,## ESPN India Edition - Menu\n\n**Main Content...,John Brewin reviews the eight matches that ult...,{'title': 'Eight matches that doomed Louis van...
31,35,ESPNW - Voices,"Is Beyonce an athlete, too? Joy Priest explore...",badminton,http://www.espn.com/espnw/voices/article/15562...,## ESPN Menu Description\n\nThe provided text ...,"Is Beyonce an athlete, too? Joy Priest explore...","{'title': 'The athleticism of Beyonce', 'conte..."
32,36,Was Cozier the last of a golden age of comment...,The sport and media landscape has changed so m...,badminton,https://www.espn.in/cricket/story/_/id/1555969...,## ESPN India Edition - Menu\n\nThe provided t...,The sport and media landscape has changed so m...,{'title': 'Was Cozier the last of a golden age...
33,37,"Liverpool vs Chelsea preview: How to watch, st...",Everything you need to know as Liverpool host ...,general,https://www.espn.in/football/story/_/id/418469...,## ESPN India Edition - Liverpool vs Chelsea P...,Everything you need to know as Liverpool host ...,{'title': 'Liverpool vs Chelsea preview: How t...
34,38,Rachin Ravindra headlines NZ's first Test win ...,Jasprit Bumrah threatened to take a wicket eve...,general,https://www.espn.in/cricket/series/19430/repor...,**ESPN India Edition - Match Summary**\n\nThe ...,Read the detailed Reports & Articles of India ...,{'title': 'Rachin Ravindra headlines NZ's firs...
35,39,Player ratings: Arsenal suffer first loss of s...,Arsenal suffered their first loss of the 2024-...,general,https://www.espn.in/football/story/_/id/418862...,## ESPN India Edition - Menu Description\n\nTh...,Arsenal suffered their first loss of the 2024-...,{'title': 'Arsenal ratings: First loss of seas...
36,40,"Bloodied but not beaten, Man United comeback s...",Man United came from behind to win against Bre...,general,https://www.espn.in/football/story/_/id/418840...,## ESPN India Edition Menu\n\nThe provided tex...,Man United came from behind to win against Bre...,{'title': 'Man United comeback shows they must...
37,41,"Pro Kabaddi League 2024-25: PKL 11 News, Sched...","PKL 11: Check all the latest scores, results, ...",general,https://www.espn.in/kabaddi/story/_/id/4184292...,## ESPN India Edition - Pro Kabaddi League Cov...,"PKL 11: Check all the latest scores, results, ...",{'title': 'Pro Kabaddi League 2024-25: PKL 11 ...

In [54]:
filtered_req_df["scrapped_news1"][1]

'Arsenal suffered their first loss of the 2024-25 Premier League season after lowlight-worthy performances from Saliba and Trossard.'

In [29]:
def create_scraped_news_with_error_handling(link):
    try:
        # Call your original scraping function (or LLM call)
        return create_scraped_news(link)  # Assuming this is your existing function
    except BadRequestError as e:
        print(f"BadRequestError for link {link}: {e}")
        return None  # Return None or some default value if an error occurs

# Apply the modified function with error handling
filtered_req_df["scrapped_news"] = filtered_req_df["full_link"].apply(create_scraped_news_with_error_handling)

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

NameError: name 'BadRequestError' is not defined

In [27]:
filtered_req_df

,index,title,summary,label,full_link
0,0,"Liverpool vs Chelsea preview: How to watch, st...",Everything you need to know as Liverpool host ...,football,https://www.espn.in/football/story/_/id/418469...
1,1,Player ratings: Arsenal suffer first loss of s...,Arsenal suffered their first loss of the 2024-...,football,https://www.espn.in/football/story/_/id/418862...
2,2,"Bloodied but not beaten, Man United comeback s...",Man United came from behind to win against Bre...,football,https://www.espn.in/football/story/_/id/418840...
3,3,Latest scores,"Results and scores from the Premier League, Ch...",football,https://www.espn.in/football/scoreboard
4,4,Rachin Ravindra headlines NZ's first Test win ...,Jasprit Bumrah threatened to take a wicket eve...,cricket,https://www.espn.in/cricket/series/19430/repor...
5,5,Cricket,"""Hope it can be an even better day for New Zea...",cricket,https://www.espn.in/cricket/
6,6,New Zealand,New Zealand captain on the importance of the w...,cricket,https://www.espn.in/cricket/team/_/id/5/new-ze...
7,7,India,Rohit Sharma looks back at India's eight-wicke...,cricket,https://www.espn.in/cricket/team/_/id/6/india
8,8,"Arctic Open: All eyes on Sindhu, Lakshya in re...",PV Sindhu and Lakshya Sen will be back on the ...,badminton,https://www.espn.in/badminton/story/_/id/41660...
9,9,news - in badminton,Lakshya Sen's debut Olympics journey came to a...,badminton,https://www.espn.in/olympics/story/_/id/407346...
10,11,News,Taiwan's government on Monday called on French...,badminton,https://www.espn.in/olympics/story/_/id/407306...
11,12,News,Taiwan's Lee Yang and Wang Chi-Lin retained th...,badminton,https://www.espn.in/olympics/story/_/id/407247...
12,13,news - in badminton,Malaysia's Aaron Chia and Soh Wooi Yik have re...,badminton,https://www.espn.in/olympics/story/_/id/407238...
13,14,news - in badminton,"Simply put, Lakshya has a great chance to win ...",badminton,https://www.espn.in/olympics/story/_/id/407232...
14,15,news - in badminton,Lovlina just couldn't find her best when she n...,badminton,https://www.espn.in/olympics/story/_/id/407221...
15,16,news - in badminton,Chiharu Shida and Nami Matsuyama claimed Japan...,badminton,https://www.espn.in/olympics/story/_/id/407156...
16,17,news - in badminton,It won't be easy for Lakshya. Axelsen is prett...,badminton,https://www.espn.in/olympics/story/_/id/407138...
17,18,news - in badminton,Lee Zii Jia remains firmly in the hunt for a m...,badminton,https://www.espn.in/olympics/story/_/id/407101...
18,19,news - in badminton,Lakshya Sen is the first Indian man to reach a...,badminton,https://www.espn.in/olympics/story/_/id/407088...
19,21,news - in badminton,Sindhu's exit from the Paris Olympics leaves h...,badminton,https://www.espn.in/olympics/story/_/id/407040...
20,22,news - in badminton,It was a mixed day for Singapore in Olympics b...,badminton,https://www.espn.in/olympics/story/_/id/407007...
21,23,news - in badminton,Sen is now only the third Indian to reach the ...,badminton,https://www.espn.in/olympics/story/_/id/407002...
22,25,news - in badminton,Sen is now only the third Indian to reach the ...,badminton,https://www.espn.in/olympics/story/_/id/406990...
23,27,news - in badminton,Satwiksairaj Rankireddy and Chirag Shetty lost...,badminton,https://www.espn.in/olympics/story/_/id/406980...
24,28,news - in badminton,Lakshya Sen vs HS Prannoy will see an all-Indi...,badminton,https://www.espn.in/olympics/story/_/id/406952...
25,29,Summer Olympics,Four Indians are in contention for three medal...,badminton,https://www.espn.in/olympics/story/_/id/406900...
26,30,Summer Olympics,Lakshya put on a masterclass of creative defen...,badminton,https://www.espn.in/olympics/story/_/id/406883...
27,31,Olympic Sports,Yeo Jia Min has ended a 12-year wait for Singa...,badminton,https://www.espn.in/olympics/story/_/id/406878...
28,32,Moment 3. Padukone wins the All England Open,Top 20 moments in Indian sports,badminton,http://espn.com/video/clip?id=16972496
29,33,'Olympic medal will be bigger than WC medals' ...,World No. 10 PV Sindhu expressed her happiness...,badminton,https://www.espn.in/badminton/story/_/id/15473...
30,34,Eight matches that doomed Louis van Gaal at Ma...,John Brewin reviews the eight matches that ult...,badminton,https://www.espn.in/football/club/manchester-u...
31,35,ESPNW - Voices,"Is Beyonce an athlete, too? Joy Priest explore...",badminton,http://www.espn.com/espnw/voices/article/15562...
32,36,Was Cozier the last of a golden age of comment...,The sport and media landscape has changed so m...,badminton,https://www.espn.in/cricket/story/_/id/1555969...
33,37,"Liverpool vs Chelsea preview: How to watch, st...",Everything you need to know as Liverpool host ...,general,https://www.espn.in/football/story/_/id/418469...
34,38,Rachin Ravindra headlines NZ's first Test win ...,Jasprit Bumrah threatened to take a wicket eve...,general,https://www.espn.in/cricket/series/19430/repor...
35,39,Player ratings: Arsenal suffer first loss of s...,Arsenal suffered their first loss of the 2024-...,general,https://www.espn.in/football/story/_/id/418862...
36,40,"Bloodied but not beaten, Man United comeback s...",Man United came from behind to win against Bre...,general,https://www.espn.in/football/story/_/id/418840...
37,41,"Pro Kabaddi League 2024-25: PKL 11 News, Sched...","PKL 11: Check all the latest scores, results, ...",general,https://www.espn.in/kabaddi/story/_/id/4184292...

In [ ]:
## Headers to prevent the bad connection issue
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
}

## setup the beautiful soup functionality
response = requests.get(URL_link, headers=headers)
bsoup = BeautifulSoup(response.content, 'html.parser')

## Grep the links in website content page
raw_links = bsoup.find_all("a")
links = []
text = []
for link in raw_links:
    links.append(link.get("href"))
    text.append(link.string)
    
## Converting lists to dataframe
raw_df = pd.DataFrame({
    "link": links,
    "label": text
})
raw_df1 = raw_df.dropna().reset_index()

rVal = raw_df1["link"].map(lambda x: x.startswith("https://"))
master_Df = raw_df1[rVal].drop("index", axis=1).reset_index().drop("index", axis=1)
# master_Df["extracted"] = master_Df["link"].apply(get_third_part)

master_Df = master_Df[(master_Df["extracted"] == keywords[0]) | (master_Df["extracted"] == self.keywords[1])]
master_Df = pd.DataFrame(master_Df)

In [ ]:
# data = WebScrappingDataGeneration(url, keywords=keywords).scrap_data()
# data = pd.DataFrame(data)
# print(data)

In [1]:
from web_scraping_news import ScrapData

                                                link  \
0  https://www.espn.in/football/league/_/name/fif...
1          https://www.espn.in/football/club/_/id/83
2            https://www.espn.co.uk/soccer/transfers
3            https://www.espn.in/football/scoreboard
4                 https://www.espn.in/football/table
5             https://www.espn.in/football/transfers

                                            label extracted
0                                  FIFA World Cup  football
1                                         See All  football
2  Check out all the latest completed major deals    soccer
3                                   Latest scores  football
4                                   League tables  football
5                                       Transfers  football

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\text_summarization\llm_newsScraping.py:30: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  output_chain = chain.run(docs)
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.co.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

                                                link  \
0  https://www.espn.in/football/league/_/name/fif...
1          https://www.espn.in/football/club/_/id/83
2            https://www.espn.co.uk/soccer/transfers
3            https://www.espn.in/football/scoreboard
4                 https://www.espn.in/football/table
5             https://www.espn.in/football/transfers

                                            label extracted  \
0                                  FIFA World Cup  football
1                                         See All  football
2  Check out all the latest completed major deals    soccer
3                                   Latest scores  football
4                                   League tables  football
5                                       Transfers  football

                                       scrapped_news
0  ## ESPN India Edition - October 27, 2023\n\n**...
1  ## Barcelona: Champions League Update and LALI...
2  ## Transfer News\n\n**Title:** Transfer Talk: ...
3  ## Soccer Scores\n\n**Date:** Saturday, Octobe...
4  ## English Premier League Table 2024-25\n\n**T...
5  ## Transfer Talk: Latest Football Transfer New...

In [13]:
from llm_newsScraping import create_scraped_news

create_scraped_news(data['link'][1])

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

ValueError: Missing some input keys: {'input_documents'}

In [2]:
URL_link = "https://www.espn.in/football/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
}

response = requests.get(URL_link, headers=headers)

bsoup = BeautifulSoup(response.content, 'html.parser')

In [3]:
from numpy import append


raw_links = bsoup.find_all("a")

links = []
text = []
for link in raw_links:
    links.append(link.get("href"))
    text.append(link.string)

In [4]:
# bsoup.find("")
df = pd.DataFrame({
    "link": links,
    "label": text
})

In [5]:
df

,link,label
0,#,Menu
1,/,ESPN
2,#,None
3,#,scores
4,#,None
...,...,...
109,http://fantasyfc.espn.com/in/9/clienthome.do,ESPN Fantasy Football
110,https://disneytermsofuse.com/english/,Terms of Use
111,https://privacy.thewaltdisneycompany.com/en/cu...,Privacy Policy
112,https://privacy.thewaltdisneycompany.com/en/cu...,Addendum to the Global Privacy Policy
113,http://preferences-mgr.truste.com/?type=espn&a...,Interest Based Ads

In [6]:
df1 = df.dropna().reset_index()

In [7]:
df1

,index,link,label
0,0,#,Menu
1,1,/,ESPN
2,3,#,scores
3,5,/olympics/,Olympic Sports
4,6,/football/,Football
...,...,...,...
81,109,http://fantasyfc.espn.com/in/9/clienthome.do,ESPN Fantasy Football
82,110,https://disneytermsofuse.com/english/,Terms of Use
83,111,https://privacy.thewaltdisneycompany.com/en/cu...,Privacy Policy
84,112,https://privacy.thewaltdisneycompany.com/en/cu...,Addendum to the Global Privacy Policy
85,113,http://preferences-mgr.truste.com/?type=espn&a...,Interest Based Ads

In [18]:
rVal = df1["link"].map(lambda x: x.startswith("https://"))
master_Df = df1[rVal].drop("index", axis=1).reset_index().drop("index", axis=1)

In [22]:
def get_third_part(link):
    parts = link.split('/')  # Split the URL by "/"
    if len(parts) > 3:       # Ensure the URL has enough parts
        return parts[3]
    return None


master_Df["extracted"] = master_Df["link"].apply(get_third_part)

In [35]:
master_Df = master_Df[(master_Df["extracted"] == "football") | (master_Df["extracted"] == "soccer")]

In [36]:
master_Df

,link,label,extracted
0,https://www.espn.in/football/league/_/name/fif...,FIFA World Cup,football
1,https://www.espn.com/soccer/scoreboard/_/date/...,See All,soccer
2,https://www.espn.in/football/club/_/id/360,See All,football
3,https://www.espn.co.uk/soccer/transfers,Check out all the latest completed major deals,soccer
4,https://www.espn.co.uk/football/table/_/league...,AFC Champions League Elite: Standings,football
5,https://www.espn.co.uk/football/scoreboard/_/l...,UEFA Champions League: Matchday 2 results,football
6,https://www.espn.co.uk/football/table/_/league...,UEFA Champions League standings,football
7,https://www.espn.in/football/scoreboard,Latest scores,football
8,https://www.espn.in/football/table,League tables,football
9,https://www.espn.in/football/transfers,Transfers,football

In [46]:
from llm_newsScraping import create_scraped_news

master_Df["scrapped_news"] = master_Df["link"].apply(create_scraped_news)

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.co.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.co.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.co.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.co.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Aathi\AppData\Local\Temp\ipykernel_2388\2286391506.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_Df["scrapped_news"] = master_Df["link"].apply(create_scraped_news)

In [47]:
master_Df["scrapped_news"][2]

"## Manchester United: A Season of Disappointment and Change\n\n**Title:** Manchester United: A Season of Disappointment and Change\n\n**Subtitle:** Ten Hag's men struggle in the Premier League, but rumors suggest major changes are on the horizon.\n\n**Description:**\n\nManchester United's miserable start to the Premier League has brought disappointment and uncertainty to the club. Currently sitting 13th, their hopes of challenging for the title have already faded. However, recent reports suggest significant changes are afoot.\n\nThe club is reportedly considering a move for Inter Milan striker Romelu Inzaghi to replace struggling manager Erik ten Hag. Additionally, speculation links them with a move for teenage wonderkid Chido Obi-Martin.\n\nTen Hag himself has come under intense scrutiny, with fans and pundits alike questioning his ability to turn the team's fortunes around. Despite recent signings and an improved performance against Everton, questions persist over the long-term direction of the club.\n\nThe team's struggles extend beyond just results. Poor performances and a lack of attacking potency have raised concerns about the quality of the squad. The defense has also been inconsistent, leaking goals at an alarming rate.\n\nDespite the challenges, Manchester United fans remain hopeful that the new owners will invest wisely and bring success back to the club. However, the upcoming months will be crucial in determining the future of the team under Ten Hag's leadership."

In [48]:
create_scraped_news(master_Df["link"][1])

d:\GenAi_Course\gen_ai_tutorial\llm_practices\venv\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.espn.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

"## Summary of Soccer Scores (October 2, 2024)\n\n**International Competitions:**\n\n* **Champions League:**\n    * Girona lose 3-2 to Feyenoord in a five-goal thriller.\n    * Manchester United lose 1-0 to Real Madrid in the opening game.\n    * Benfica defeat Atlético Madrid 4-0.\n* **Europa League:**\n    * Guimaraes secure a 1-0 win against NK Celje.\n* **MLS:**\n    * Atlanta United FC and CF Montréal draw 10-10.\n    * Charlotte FC defeat Chicago Fire FC 3-1.\n\n**National Competitions:**\n\n* **English Championship:**\n    * Preston North End and Watford draw 0-0.\n* **League One:**\n    * Union Omaha defeats Spokane Velocity FC 3-1.\n* **USL Championship:**\n    * Louisville City FC defeat Miami FC 3-0.\n* **USL League One:**\n    * Union Omaha defeats Spokane Velocity FC 3-1.\n* **Mexican Liga de Expansión MX:**\n    * Atlético Morelia and Celaya draw 3-3.\n\n**Other News:**\n\n* FIFA adjusts transfer rules for the upcoming Club World Cup in the United States.\n* Deschamps explains his decision not to include Mbappe in France's squad due to fitness concerns.\n* Laurens expresses concern over Atletico Madrid's heavy loss to Benfica in the Champions League.\n\n**Additional Highlights:**\n\n* Several other league matches and cup games took place, with various results.\n* ESPN provides updates on player transfers and upcoming competitions."